ROUTINE AoC2020Day21

Start() PUBLIC {
	s input="/irisdev/app/inputs/input21.txt"
	d readInput(input, .in)

	s ans1 = $$p1(.in)
	return ans1
}

p1(in) PUBLIC {
    s ans=0
    return ans
}

readInput(input, result) PUBLIC {
	set file = ##class(%Stream.FileCharacter).%New()
	s sc = file.LinkToFile(input)
	s i = 0
	while 'file.AtEnd {
        s i = i+1
        s result(i)=$translate(file.ReadLine(), $c(13))
	}
	s result = i
}

