ROUTINE AoC2020Day23

Start() PUBLIC {
	s input="/irisdev/app/inputs/input23.txt"
	d readInput(input, .in)

	s ans1=$$p1(in)
	
    s ans2=0
	return ans1
}

p1(in) PUBLIC {
	s ans=0

	return ans
}

p2(in) PUBLIC {
    s ans=0
	return ans
}


readInput(input, p1) PUBLIC {
	s p1="", p2=""
	set file = ##class(%Stream.FileCharacter).%New()
	s sc = file.LinkToFile(input)
	s i=0
	while 'file.AtEnd {
        s i=i+1
		s curr=$translate(file.ReadLine(), $c(13))
        s p1(i)=curr
	}
	s p1=i
}