ROUTINE AoC2021Day13

Start() public {
	d readInput("/irisdev/app/inputs/2021/13.in", .input)

    return $$p1(.input)_"^"_$$p2(.input)
}

p1(g) public {
	s t = 0

	return t
}

p2(g) public {
	s t = 0

	return t
}

readInput(input, result) PUBLIC {
	set file = ##class(%Stream.FileCharacter).%New()
	s sc = file.LinkToFile(input)
	s i = 0
	while 'file.AtEnd {
        s i=i+1
		s line = $translate(file.ReadLine(), $c(13))
		s result(i) = line
	}
    s result = i
}